### ISSUE TITLE
actualizaciones de base de datos de ITX stock

### ISSUE THREAD

**Issue by santiagohleites** [enorrmann/ixprojects#4]
1_la posibilidad de obtener un listado en Excel del ítem listar componentes.
2_homogeneizar la presentación de las diferentes pantallas, las que se generaron con la carga de nuevos componentes no se visualizan en su totalidad, hay que modificar la visualización para acceder a los botones de ver, editar y eliminar.
3_agregar elementos de búsqueda por palabra clave (sfp, xfp, x inf, por ejemplo)
4_la posibilidad de poder ordenar el listado agrupado por fabricantes.
5_cuando se ingresan componentes nuevos en la del shelter hay un espacio en blanco que debería ser eliminado.

**Comment by enorrmann** [comment]
lo muevo al proyecto correspondiente
https://github.com/enorrmann/ix/issues/1
